services:
  mssql:
    container_name: mssql-server-demo
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "5434:1433"
    environment:
      - SA_PASSWORD=admin123!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    volumes: 
      - mssql-volume:/var/opt/mssql
    networks:
      - sv-bank
  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq-volume:/var/lib/rabbitmq
    networks:
      - sv-bank
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  transaction-service-init:
     container_name: migration
     build:
       context: ./TransactionService
       dockerfile: ./Dockerfile.Migration
     environment:
        - ConnectionStrings__BankSqlConnection=${CONNECTIONSTRINGS_BANKSQLCONNECTION}
     depends_on:
        - mssql
     networks:
       - sv-bank
     command: >
      /bin/sh -c "
      until /opt/mssql-tools/bin/sqlcmd -S ${DB_HOST} -U ${DB_USER} -P '${SA_PASSWORD}' -Q 'SELECT 1' &> /dev/null; do
        echo 'Checking Sql Server...';
        sleep 5;
      done;
      echo 'SQL Sql ready';
      ./efbundle ${MIGRATIONNAME:-''}
      "
  transaction-service:
        container_name: transaction-service
        environment:
            - ConnectionStrings__BankSqlConnection=${CONNECTIONSTRINGS_BANKSQLCONNECTION}
            - BusConfiguration__RabbitMQEnabled=${BUSCONFIGURATION_RABBITMQENABLED}
            - BusConfiguration__RabbitMQConnectionString=${BUSCONFIGURATION_RABBITMQCONNECTIONSTRING}
            - BusConfiguration__KafkaConnectionString=${BUSCONFIGURATION_KAFKACONNECTIONSTRING}
        build:
            context: ./TransactionService
            dockerfile: Dockerfile
        ports:
            - 6010:80
        networks:
            - sv-bank
        depends_on: 
            rabbitmq:
               condition: service_healthy
            mssql:
               condition: service_started
  transaction-worker:
        container_name: transaction-worker
        environment:
            - ConnectionStrings__BankSqlConnection=${CONNECTIONSTRINGS_BANKSQLCONNECTION}
            - BusConfiguration__RabbitMQEnabled=${BUSCONFIGURATION_RABBITMQENABLED}
            - BusConfiguration__RabbitMQConnectionString=${BUSCONFIGURATION_RABBITMQCONNECTIONSTRING}
            - BusConfiguration__KafkaConnectionString=${BUSCONFIGURATION_KAFKACONNECTIONSTRING}
        build:
            context: ./TransactionService
            dockerfile: ./Dockerfile.Worker
        networks:
            - sv-bank
        depends_on: 
            rabbitmq:
               condition: service_healthy
            mssql:
               condition: service_started
  antifroud-worker:
        container_name: antifroud-worker
        environment:
            - ConnectionStrings__BankSqlConnection=${CONNECTIONSTRINGS_BANKSQLCONNECTION}
            - BusConfiguration__RabbitMQEnabled=${BUSCONFIGURATION_RABBITMQENABLED}
            - BusConfiguration__RabbitMQConnectionString=${BUSCONFIGURATION_RABBITMQCONNECTIONSTRING}
            - BusConfiguration__KafkaConnectionString=${BUSCONFIGURATION_KAFKACONNECTIONSTRING}
        build:
            context: ./AntifraudService
            dockerfile: ./DockerfileAntifroud.Worker
        networks:
            - sv-bank
        depends_on: 
            rabbitmq:
               condition: service_healthy
            mssql:
               condition: service_started
volumes:
  mssql-volume:
    driver: local
  rabbitmq-volume:
    driver: local

networks:
  sv-bank:
    name: sv-bank